name: Create PR from dev to qa

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - dev            # Runs whenever code is pushed to dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create or update PR from dev → qa
        run: |
          # Check if a PR already exists
          existing_pr=$(gh pr list --base qa --head dev --state open --json number --jq '.[0].number')

          if [ -n "$existing_pr" ]; then
            echo "🔄 Pull request #$existing_pr already exists — updating..."
            gh pr edit "$existing_pr" --title "Sync dev → qa" --body "Automated PR to merge latest changes from dev into qa."
          else
            echo "🆕 Creating new pull request from dev → qa..."
            gh pr create \
              --base qa \
              --head dev \
              --title "Sync dev → qa" \
              --body "Automated pull request to merge latest changes from dev into qa."
          fi
