name: Promote Dev to QA

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-promote:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Raise PR from dev → qa
        run: |
          gh pr create \
            --base qa \
            --head dev \
            --title "Auto promotion: dev → qa" \
            --body "This is an automated promotion PR generated after merging into the dev branch. Verify and merge once ready for QA deployment."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
