name: Promote Dev to QA

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync QA with Dev
        run: |
          git checkout qa
          git merge --no-ff dev -m "Sync qa with dev"
          git push origin qa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}