name: Promote Dev to QA

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "PR: Create"
        if: github.event.pull_request.merged == true
        run: gh pr create --base qa --head dev --title "Merge dev into qa" --body "This pull request was created by a GitHub Action."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}