name: Promote Dev to QA

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "PR: Create"
        if: github.event.created
        run: gh pr create --base qa --title "Merge ${{ github.ref_name }} into flux" --body "This pull request was created by a Github Action."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}